env:
  node: true
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'compat'
  - 'react'
  - 'react-hooks'
ignorePatterns:
  - '**/public/wasm'
  - '**/src/wasm'
  - 'node_modules'
rules:
  indent:
    - error
    - 2
    - ignoreComments: true
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - allowTemplateLiterals: true
      avoidEscape: true
  '@typescript-eslint/no-unused-vars':
    - warn
    - vars: all
      args: none
      varsIgnorePattern: React
  '@typescript-eslint/no-empty-function':
    - error
  no-unused-vars:
    - warn
    - vars: all
      args: none
      ignoreRestSiblings: false
      caughtErrors: none
      varsIgnorePattern: React
  semi:
    - error
    - never
  max-len:
    - error
    - code: 80
      ignoreComments: true
      ignoreStrings: true
      ignoreUrls: true
      ignoreRegExpLiterals: true
  eol-last:
    - error
    - always
  arrow-spacing:
    - error
    - before: true
      after: true
  keyword-spacing:
    - error
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  space-before-blocks:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  object-curly-newline:
    - error
    - ImportDeclaration:
        multiline: true
        minProperties: 3
      ExportDeclaration:
        multiline: true
        minProperties: 3
  comma-spacing:
    - error
    - before:
        false
      after:
        true
  spaced-comment:
    - error
    - always
    - exceptions:
      - '-'
      - '+'
      block:
        balanced: true
      markers:
        - '/'
        - '#'
        - '-'
        - '='
  no-trailing-spaces:
    - error
  no-warning-comments:
    - warn
    - terms:
      - TODO
      - FIXME
      location: anywhere
  no-multiple-empty-lines:
    - error
    - max: 1
      maxEOF: 1
  no-unneeded-ternary:
    - warn

# React
  react/jsx-tag-spacing:
    - 2
    - beforeSelfClosing: always
  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 1
  jsx-quotes:
    - error
    - prefer-single
