name: Build

on:
  push:
    branches: ["trunk"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm build
          touch dist/.nojekyll

      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: dist
          retention-days: 1