name: Deploy Web

on:
  workflow_run:
    workflows: ["Build"]
    branches: ["trunk"]
    types:
      - completed

permissions:
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-dist
          path: ./dist
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4